name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: high
          deny-licenses: 'GPL-1.0-or-later, LGPL-2.0-or-later'
          comment-summary-in-pr: true

  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run security audit
        run: |
          npm audit
          if [ $? -eq 1 ]; then
            echo "Security vulnerabilities found!"
            npm audit fix
            git config --global user.name 'GitHub Actions Bot'
            git config --global user.email 'actions@github.com'
            git add package*.json
            git commit -m "fix: npm audit automatic fixes"
            git push
          fi
